/*
//* The purpose of this file is to create a mapping of the possible api weather condition
//* response to the respective background/icon
*/

interface WeatherIconsInterface {
    day: { [key: string]: string };
    night: { [key: string]: string };
}

interface BackgroundImagesInterface {
    sunrise: { [key: string]: string };
    sunset: { [key: string]: string };
    day: { [key: string]: string };
    night: { [key: string]: string };
}

export const WEATHER_ICONS: WeatherIconsInterface = {
    day: {
        Sunny: "/icons/Weather-Icons/day/sunny.png",
        "Partly cloudy": "/icons/Weather-Icons/day/partly-cloudy-day.png",
        Cloudy: "/icons/Weather-Icons/day/partly-cloudy-day.png",
        Overcast: "/icons/Weather-Icons/overcast.png",
        Mist: "/icons/Weather-Icons/day/mist.png",
        "Patchy rain possible": "/icons/Weather-Icons/drizzle.png",
        "Patchy snow possible": "/icons/Weather-Icons/snowing.png",
        "Patchy sleet possible": "/icons/Weather-Icons/rain-with-snow.png",
        "Patchy freezing drizzle possible": "/icons/Weather-Icons/rain-with-snow.png",
        "Thundery outbreaks possible": "/icons/Weather-Icons/thunderstorm.png",
        "Blowing snow": "/icons/Weather-Icons/snowing.png",
        Blizzard: "/icons/Weather-Icons/blizzard.png",
        Fog: "/icons/Weather-Icons/fog.png",
        "Freezing fog": "/icons/Weather-Icons/fog.png",
        "Patchy light drizzle": "/icons/Weather-Icons/rain-with-snow.png",
        "Light drizzle": "/icons/Weather-Icons/drizzle.png",
        "Freezing drizzle": "/icons/Weather-Icons/rain-with-snow.png",
        "Heavy freezing drizzle": "/icons/Weather-Icons/rain-with-snow.png",
        "Patchy light rain": "/icons/Weather-Icons/day/light-rain-day.png",
        "Light rain": "/icons/Weather-Icons/day/light-rain-day.png",
        "Moderate rain at times": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Moderate rain": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Heavy rain at times": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Heavy rain": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Light freezing rain": "/icons/Weather-Icons/rain-with-snow.png",
        "Moderate or heavy freezing rain": "/icons/Weather-Icons/rain-with-snow.png",
        "Light sleet": "/icons/Weather-Icons/rain-with-snow.png",
        "Moderate or heavy sleet": "/icons/Weather-Icons/rain-with-snow.png",
        "Patchy light snow": "/icons/Weather-Icons/snowing.png",
        "Light snow": "/icons/Weather-Icons/snowing.png",
        "Patchy moderate snow": "/icons/Weather-Icons/snowing.png",
        "Moderate snow": "/icons/Weather-Icons/snowing.png",
        "Patchy heavy snow": "/icons/Weather-Icons/blizzard.png",
        "Heavy snow": "/icons/Weather-Icons/blizzard.png",
        "Ice pellets": "/icons/Weather-Icons/ice-pellets.png",
        "Light rain shower": "/icons/Weather-Icons/day/light-rain-day.png",
        "Moderate or heavy rain shower": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Torrential rain shower": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Light sleet showers": "/icons/Weather-Icons/day/light-rain-day.png",
        "Moderate or heavy sleet showers": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Light snow showers": "/icons/Weather-Icons/snowing.png",
        "Moderate or heavy snow showers": "/icons/Weather-Icons/snowing.png",
        "Light showers of ice pellets": "/icons/Weather-Icons/ice-pellets.png",
        "Moderate or heavy showers of ice pellets": "/icons/Weather-Icons/ice-pellets.png",
        "Patchy light rain with thunder": "/icons/Weather-Icons/thunderstorm.png",
        "Moderate or heavy rain with thunder": "/icons/Weather-Icons/thunderstorm.png",
        "Patchy light snow with thunder": "/icons/Weather-Icons/snowing.png",
        "Moderate or heavy snow with thunder": "/icons/Weather-Icons/snowing.png",
    },

    night: {
        Clear: "/icons/Weather-Icons/night/clear.png",
        "Partly cloudy": "/icons/Weather-Icons/night/cloudy-night.png",
        Cloudy: "/icons/Weather-Icons/night/cloudy-night.png",
        Overcast: "/icons/Weather-Icons/overcast.png",
        Mist: "/icons/Weather-Icons/night/night-mist.png",
        "Patchy rain possible": "/icons/Weather-Icons/drizzle.png",
        "Patchy snow possible": "/icons/Weather-Icons/snowing.png",
        "Patchy sleet possible": "/icons/Weather-Icons/rain-with-snow.png",
        "Patchy freezing drizzle possible": "/icons/Weather-Icons/rain-with-snow.png",
        "Thundery outbreaks possible": "/icons/Weather-Icons/thunderstorm.png",
        "Blowing snow": "/icons/Weather-Icons/snowing.png",
        Blizzard: "/icons/Weather-Icons/blizzard.png",
        Fog: "/icons/Weather-Icons/fog.png",
        "Freezing fog": "/icons/Weather-Icons/fog.png",
        "Patchy light drizzle": "/icons/Weather-Icons/rain-with-snow.png",
        "Light drizzle": "/icons/Weather-Icons/drizzle.png",
        "Freezing drizzle": "/icons/Weather-Icons/rain-with-snow.png",
        "Heavy freezing drizzle": "/icons/Weather-Icons/rain-with-snow.png",
        "Patchy light rain": "/icons/Weather-Icons/raining.png",
        "Light rain": "/icons/Weather-Icons/raining.png",
        "Moderate rain at times": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Moderate rain": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Heavy rain at times": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Heavy rain": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Light freezing rain": "/icons/Weather-Icons/rain-with-snow.png",
        "Moderate or heavy freezing rain": "/icons/Weather-Icons/rain-with-snow.png",
        "Light sleet": "/icons/Weather-Icons/rain-with-snow.png",
        "Moderate or heavy sleet": "/icons/Weather-Icons/rain-with-snow.png",
        "Patchy light snow": "/icons/Weather-Icons/snowing.png",
        "Light snow": "/icons/Weather-Icons/snowing.png",
        "Patchy moderate snow": "/icons/Weather-Icons/snowing.png",
        "Moderate snow": "/icons/Weather-Icons/snowing.png",
        "Patchy heavy snow": "/icons/Weather-Icons/blizzard.png",
        "Heavy snow": "/icons/Weather-Icons/blizzard.png",
        "Ice pellets": "/icons/Weather-Icons/ice-pellets.png",
        "Light rain shower": "/icons/Weather-Icons/raining.png",
        "Moderate or heavy rain shower": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Torrential rain shower": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Light sleet showers": "/icons/Weather-Icons/raining.png",
        "Moderate or heavy sleet showers": "/icons/Weather-Icons/moderateORheavy-rain.png",
        "Light snow showers": "/icons/Weather-Icons/snowing.png",
        "Moderate or heavy snow showers": "/icons/Weather-Icons/snowing.png",
        "Light showers of ice pellets": "/icons/Weather-Icons/ice-pellets.png",
        "Moderate or heavy showers of ice pellets": "/icons/Weather-Icons/ice-pellets.png",
        "Patchy light rain with thunder": "/icons/Weather-Icons/thunderstorm.png",
        "Moderate or heavy rain with thunder": "/icons/Weather-Icons/thunderstorm.png",
        "Patchy light snow with thunder": "/icons/Weather-Icons/snowing.png",
        "Moderate or heavy snow with thunder": "/icons/Weather-Icons/snowing.png",
    },
};

export const BACKGROUND_IMGS: BackgroundImagesInterface = {
    sunrise: {
        clear: "/images/HeroBackgrounds/sunrise.jpg",
        raining: "/images/HeroBackgrounds/raining-day.jpg",
    },

    sunset: {
        clear: "/images/HeroBackgrounds/sunset.jpg",
        raining: "/images/HeroBackgrounds/sunset-rain.jpg",
    },

    day: {
        Sunny: "/images/HeroBackgrounds/clear-day.jpg",
        "Partly cloudy": "/images/HeroBackgrounds/cloudy-day.jpeg",
        Cloudy: "/images/HeroBackgrounds/cloudy-day.jpeg",
        Overcast: "/images/HeroBackgrounds/overcast.jpg",
        Mist: "/images/HeroBackgrounds/fog-day.jpeg",
        "Patchy rain possible": "/images/HeroBackgrounds/raining-day.jpg",
        "Patchy snow possible": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy sleet possible": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy freezing drizzle possible": "/images/HeroBackgrounds/snowing.jpg",
        "Thundery outbreaks possible": "/images/HeroBackgrounds/overcast.jpg",
        "Blowing snow": "/images/HeroBackgrounds/snowing.jpg",
        Blizzard: "/images/HeroBackgrounds/snowing.jpg",
        Fog: "/images/HeroBackgrounds/fog-day.jpeg",
        "Freezing fog": "/images/HeroBackgrounds/fog-day.jpeg",
        "Patchy light drizzle": "/images/HeroBackgrounds/raining-day.jpg",
        "Light drizzle": "/images/HeroBackgrounds/raining-day.jpg",
        "Freezing drizzle": "/images/HeroBackgrounds/raining-day.jpg",
        "Heavy freezing drizzle": "/images/HeroBackgrounds/raining-day.jpg",
        "Patchy light rain": "/images/HeroBackgrounds/raining-day.jpg",
        "Light rain": "/images/HeroBackgrounds/raining-day.jpg",
        "Moderate rain at times": "/images/HeroBackgrounds/raining-day.jpg",
        "Moderate rain": "/images/HeroBackgrounds/raining-day.jpg",
        "Heavy rain at times": "/images/HeroBackgrounds/raining-day.jpg",
        "Heavy rain": "/images/HeroBackgrounds/raining-day.jpg",
        "Light freezing rain": "/images/HeroBackgrounds/raining-day.jpg",
        "Moderate or heavy freezing rain": "/images/HeroBackgrounds/raining-day.jpg",
        "Light sleet": "/images/HeroBackgrounds/raining-day.jpg",
        "Moderate or heavy sleet": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy light snow": "/images/HeroBackgrounds/snowing.jpg",
        "Light snow": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy moderate snow": "/images/HeroBackgrounds/snowing.jpg",
        "Moderate snow": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy heavy snow": "/images/HeroBackgrounds/snowing.jpg",
        "Heavy snow": "/images/HeroBackgrounds/snowing.jpg",
        "Ice pellets": "/images/HeroBackgrounds/raining-day.jpg",
        "Light rain shower": "/images/HeroBackgrounds/raining-day.jpg",
        "Moderate or heavy rain shower": "/images/HeroBackgrounds/heavy-rain.jpg",
        "Torrential rain shower": "/images/HeroBackgrounds/heavy-rain.jpg",
        "Light sleet showers": "/images/HeroBackgrounds/raining-day.jpg",
        "Moderate or heavy sleet showers": "/images/HeroBackgrounds/snowing.jpg",
        "Light snow showers": "/images/HeroBackgrounds/snowing.jpg",
        "Moderate or heavy snow showers": "/images/HeroBackgrounds/snowing.jpg",
        "Light showers of ice pellets": "/images/HeroBackgrounds/snowing.jpg",
        "Moderate or heavy showers of ice pellets": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy light rain with thunder": "/images/HeroBackgrounds/heavy-rain.jpg",
        "Moderate or heavy rain with thunder": "/images/HeroBackgrounds/heavy-rain.jpg",
        "Patchy light snow with thunder": "/images/HeroBackgrounds/snowing.jpg",
        "Moderate or heavy snow with thunder": "/images/HeroBackgrounds/snowing.jpg",
    },

    night: {
        Clear: "/images/HeroBackgrounds/clear-night.jpg",
        "Partly cloudy": "/images/HeroBackgrounds/cloudy-night.jpg",
        Cloudy: "/images/HeroBackgrounds/cloudy-night.jpg",
        Overcast: "/images/HeroBackgrounds/overcast.jpg",
        Mist: "/images/HeroBackgrounds/mist-fog-night.jpg",
        "Patchy rain possible": "/images/HeroBackgrounds/raining-night.jpg",
        "Patchy snow possible": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy sleet possible": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy freezing drizzle possible": "/images/HeroBackgrounds/snowing.jpg",
        "Thundery outbreaks possible": "/images/HeroBackgrounds/overcast.jpg",
        "Blowing snow": "/images/HeroBackgrounds/snowing.jpg",
        Blizzard: "/images/HeroBackgrounds/snowing.jpg",
        Fog: "/images/HeroBackgrounds/mist-fog-night.jpg",
        "Freezing fog": "/images/HeroBackgrounds/mist-fog-night.jpg",
        "Patchy light drizzle": "/images/HeroBackgrounds/raining-night.jpg",
        "Light drizzle": "/images/HeroBackgrounds/raining-night.jpg",
        "Freezing drizzle": "/images/HeroBackgrounds/raining-night.jpg",
        "Heavy freezing drizzle": "/images/HeroBackgrounds/raining-night.jpg",
        "Patchy light rain": "/images/HeroBackgrounds/raining-night.jpg",
        "Light rain": "/images/HeroBackgrounds/raining-night.jpg",
        "Moderate rain at times": "/images/HeroBackgrounds/raining-night.jpg",
        "Moderate rain": "/images/HeroBackgrounds/raining-night.jpg",
        "Heavy rain at times": "/images/HeroBackgrounds/storm-night.jpg",
        "Heavy rain": "/images/HeroBackgrounds/storm-night.jpg",
        "Light freezing rain": "/images/HeroBackgrounds/raining-night.jpg",
        "Moderate or heavy freezing rain": "/images/HeroBackgrounds/raining-night.jpg",
        "Light sleet": "/images/HeroBackgrounds/raining-night.jpg",
        "Moderate or heavy sleet": "/images/HeroBackgrounds/raining-night.jpg",
        "Patchy light snow": "/images/HeroBackgrounds/snowing.jpg",
        "Light snow": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy moderate snow": "/images/HeroBackgrounds/snowing.jpg",
        "Moderate snow": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy heavy snow": "/images/HeroBackgrounds/snowing.jpg",
        "Heavy snow": "/images/HeroBackgrounds/snowing.jpg",
        "Ice pellets": "/images/HeroBackgrounds/raining-day.jpg",
        "Light rain shower": "/images/HeroBackgrounds/raining-night.jpg",
        "Moderate or heavy rain shower": "/images/HeroBackgrounds/storm-night.jpg",
        "Torrential rain shower": "/images/HeroBackgrounds/storm-night.jpg",
        "Light sleet showers": "/images/HeroBackgrounds/raining-night.jpg",
        "Moderate or heavy sleet showers": "/images/HeroBackgrounds/raining-night.jpg",
        "Light snow showers": "/images/HeroBackgrounds/snowing.jpg",
        "Moderate or heavy snow showers": "/images/HeroBackgrounds/snowing.jpg",
        "Light showers of ice pellets": "/images/HeroBackgrounds/snowing.jpg",
        "Moderate or heavy showers of ice pellets": "/images/HeroBackgrounds/snowing.jpg",
        "Patchy light rain with thunder": "/images/HeroBackgrounds/storm-night.jpg",
        "Moderate or heavy rain with thunder": "/images/HeroBackgrounds/storm-night.jpg",
        "Patchy light snow with thunder": "/images/HeroBackgrounds/snowing.jpg",
        "Moderate or heavy snow with thunder": "/images/HeroBackgrounds/snowing.jpg",
    },
};
